### ISSUE TITLE
Instant deletion

### ISSUE THREAD

**Issue by Osprey010** [ParrotSec/mimikatz#1]
as soon as I click download on the code windows falgs it as trojan and instantly deleats it  :(

**Comment by PalinuroSec** [comment]
hi, this source repository is meant to maintain the files needed to build the deb package for the mimikatz tool and keep it updated over time. the package is then added to the repository of the parrot operating system and it was never meant to be downloaded from this git repo via the browser

mimikatz is a well known malware, and your browser security features are designed to prevent you from downloading and running it
