### ISSUE TITLE
ummmmmmmm

### ISSUE THREAD

**Issue by Mati278** [ParrotSec/mimikatz#9]
why this repo is marked as malicious by google
https://twitter.com/endermanch/status/1731347292006097083

**Comment by Mav3r1ck0x1** [comment]
Are you retarded or something?

**Comment by PalinuroSec** [comment]
> why this repo is marked as malicious by google https://twitter.com/endermanch/status/1731347292006097083

please pay attention to the sarcastic nature of the original tweet, which criticizes the ability to distinguish between malicious malware and popular penetration testing tools
